language: python
sudo: required

services:
  - postgresql
  - redis
  - docker

install:
  - bash bin/travis-build.bash
  - pip install coveralls
  - pip freeze
script: bash bin/travis-run.bash

stages:
  - Flake8
  - Tests

jobs:
  include:
#    - stage: Flake8
#      python: 3.6
#      env: FLAKE8=True
#      install:
#        - pip install flake8==3.5.0
#        - pip install pycodestyle==2.3.0
#      script:
#        - flake8 --version
#        # stop the build if there are Python syntax errors or undefined names
#        - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --exclude ckan
#        # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
#        - flake8 . --count --max-line-length=127 --statistics --exclude ckan --exit-zero


    - stage: Tests
      python: "2.7"
      env: CKANVERSION=2.9
      services:
          - postgresql
          - redis
          - docker

    - python: "3.8"
      env: CKANVERSION=2.9
      services:
          - postgresql
          - redis
          - docker


after_success:
    - coveralls

cache:
  directories:
    - $HOME/.cache/pip